auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Xeraph
url: http://wangdelp.github.io
feed: /atom.xml
author_info: <a href="http://beiyuu.com/">BeiYuu</a>

comments :
  provider : disqus
  disqus :
    shortname : wangde
    
disqus_shortname: wangde
